#!/bin/bash
sudo rm -rf /home/ec2-user/java_project
# Clone the repository
sudo git clone https://github.com/devopsacademy2015/java_project.git /home/ec2-user/java_project
sudo cd /home/ec2-user/java_project
# Build the project using Maven from the correct directory
sudo mvn clean install
sudo cp java_project.war /home/ec2-user/tomcat/webapps
sudo cd /home/ec2-user/tomcat/bin ; sh shutdown.sh ; sh startup.sh
